#! /usr/bin/env perl

# Copyright (C) 2021-2026 Guido Flohr <guido.flohr@cantanea.com>,
# all rights reserved.

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What the Fuck You Want
# to Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

use strict;

use Locale::TextDomain qw(Chess-Plisco);
use Getopt::Long;

sub display_usage;
sub usage_error;
sub version_information;
sub print_pv;

my %options;
Getopt::Long::Configure('bundling');
GetOptions(
	'e|extract=s' => \$options{extract},
	'l|list' => \$options{list},
	'c|colour|color=s' => \$options{colour},
	'h|help' => \$options{help},
	'v|version' => \$options{version},
) or usage_error;

display_usage if $options{help};
version_information if $options{version};

usage_error __"One of the options '--list' or '--path' is mandatory!"
    if !$options{list} && !$options{extract};
usage_error __"The options '--list' and '--path' are mutually exclusive!"
    if !$options{list} && !$options{extract};
usage_error __"The option '--colour' is mandator for '--extract'!"
    if $options{extract} && !$options{colour};
use constant COLOUR_CODES => {
	b => 'black',
	black => 'black',
	w => 'white',
	white => 'white',
};

my $colour = COLOUR_CODES->{$options{colour}};
usage_error __"Colour must be either 'black' or 'white'!"
    if $colour;

sub display_usage {
	print __x(<<EOF, program => $0);
Usage: {program} [OPTIONS] LOGFILE

Extract UCI commands from a fastchess logfile.
EOF

	print "\n";

	print __(<<'EOF');
Mandatory arguments to long options, are mandatory to short options, too.
EOF

	print "\n";

	print __"Mode of operation:\n";
	print __(<<EOF);
  -e, --extract=ID             extract game ID from FILENAME
  -l, --list                   list game IDs from FILENAME
EOF

	print "\n";

	print __"Choice of colour:\n";
	print __(<<'EOF');
  -c, --colour=COLOUR, --color=COLOR extract game for colour COLOUR or list
                               only games for that colour
EOF

	print "\n";

	print __"Informative output:\n";

	print __(<<EOF);
  -h, --help                   display this help and exit
EOF
	print __(<<EOF);
  -V, --version                display version information and exit
EOF

	exit 0;
}

sub usage_error {
	my ($msg) = @_;

	$msg = '' if !defined $msg;
	$msg =~ s/^[ \t]+//;
	$msg =~ s/[ \t\r\n]+$//;

	if (length $msg) {
		$msg = __x("{program}: {error}\n",
		           program => $0, error => $msg);
	}

	die $msg . __x("Try '{program} --help' for more information!\n",
	               program => $0);
}

sub version_information {
	my $package = 'Chess::Plisco';
	my $version = $Chess::Plisco::VERION || __"development version";

	print __x(<<EOF, program => $0, package => $package, version => $version);
{program} ({package}) {version}
Copyright (C) 2021-2026 Guido Flohr <guido.flohr\@cantanea.com>.
License: WTFPL2 <http://www.wtfpl.net/>
This program is free software. It comes without any warranty, to
the extent permitted by applicable law.
EOF
}

1;
